Unit test2201
Ievgenii-Cudrin/Net.Practise pull request #9
Opened 2021-01-25 10:15 UTC by Ievgenii-Cudrin

2021-02-10 20:57 UTC, DmytroZol commented on Practice1101/SomeBusinessService/Services/MainBusinessLogicService.cs
> +        public void Update(Product product, string name)
Метод Update выглядит следующим образом 
        public void Update(Product product, string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var updatedProduct = _dBManager.Get(name);
                if (updatedProduct.LastUpdated < DateTime.Now)
                {
                    _dBManager.Update(product, name);
                }
                else
                {
                    throw new ArgumentNullException();
                }
            }
            else
            {
                throw new ArgumentNullException();
            }
        }

обновите пожалйста код и тесты к методу

2021-02-10 20:59 UTC, DmytroZol requested changes
Настройте гит игнор файл для того что бы не попадали в репозиторий системные файлы и dll. Обновите код метода Update и тесты к нему.

2021-02-24 09:49 UTC, Ievgenii-Cudrin commented on Practice1101/SomeBusinessService/Services/MainBusinessLogicService.cs
> +        public void Update(Product product, string name)
Обновил метод и добавил тесты к нему.

2021-02-24 19:15 UTC, DmytroZol approved these changes
Хорошие тесты. На будущее больше практики и стараться делать как можно красивее и лаконичнее.

2021-02-24 19:21 UTC, merged